# Generated by Django 4.0.6 on 2022-08-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_tags_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.CharField(default=1, max_length=60, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
