# Generated by Django 4.0.6 on 2022-08-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_short_description_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.CharField(max_length=110, verbose_name='Описание'),
        ),
    ]
