# Generated by Django 4.0.6 on 2022-07-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_special_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(max_length=250, upload_to='')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('short_description', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=150)),
                ('about_us', models.TextField(max_length=2500)),
                ('privacy_policy', models.TextField(max_length=2500)),
                ('orders_and_returns', models.TextField(max_length=2500)),
                ('terms_and_conditions', models.TextField(max_length=2500)),
            ],
            options={
                'verbose_name': 'Информация о магазине',
                'verbose_name_plural': 'Информация о магазине',
            },
        ),
    ]
