# Generated by Django 4.0.6 on 2022-08-05 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0008_product_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveIntegerField(verbose_name='Телефон')),
                ('birth_date', models.DateTimeField(blank=True, verbose_name='Дата рождения')),
                ('photo', models.ImageField(upload_to=user.models.get_user_photo_path, verbose_name='Фото')),
                ('newsletter_subscription', models.BooleanField(verbose_name='Подписка')),
                ('address_country', models.CharField(blank=True, max_length=60, verbose_name='Страна')),
                ('address_city', models.CharField(blank=True, max_length=60, verbose_name='Город')),
                ('address_street', models.CharField(blank=True, max_length=100, verbose_name='Улица, дом, квартира')),
                ('address_zip', models.PositiveIntegerField(blank=True, verbose_name='Почтовый индекс')),
                ('user_comments', models.TextField(blank=True, verbose_name='Комментарии пользователя')),
                ('store_comments', models.TextField(blank=True, verbose_name='Комментарии магазина')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ManyToManyField(blank=True, to='store.product', verbose_name='Желания')),
            ],
        ),
    ]
