# Generated by Django 4.0.6 on 2022-08-05 12:55

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='newsletter_subscription',
            field=models.BooleanField(default=True, verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.PositiveIntegerField(blank=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=user.models.get_user_photo_path, verbose_name='Фото'),
        ),
    ]
