# Generated by Django 4.0.6 on 2022-08-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_sale'),
        ('user', '0004_alter_profile_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(to='store.product', verbose_name='Желания'),
        ),
    ]
