# Generated by Django 4.0.6 on 2022-08-09 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_remove_profile_address_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wishlist',
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_country_city',
            field=models.CharField(max_length=100, null=True, verbose_name='Страна, город'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
