# Generated by Django 4.0.6 on 2022-08-05 12:58

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_sale'),
        ('user', '0003_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_city',
            field=models.CharField(max_length=60, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_country',
            field=models.CharField(max_length=60, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_street',
            field=models.CharField(max_length=100, null=True, verbose_name='Улица, дом, квартира'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_zip',
            field=models.PositiveIntegerField(null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='newsletter_subscription',
            field=models.BooleanField(default=True, null=True, verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.PositiveIntegerField(null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to=user.models.get_user_photo_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='store_comments',
            field=models.TextField(null=True, verbose_name='Комментарии магазина'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_comments',
            field=models.TextField(null=True, verbose_name='Комментарии пользователя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(null=True, to='store.product', verbose_name='Желания'),
        ),
    ]
